plugins {
	id 'java-library'
	id 'maven-publish'
	id 'net.neoforged.moddev' version "${moddevgradle_version}"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
}

neoForge {
	version = project.neo_version

	runs {
		client {
			client()
		}
		server {
			server()
		}
		clientData {
			clientData()
		}
	}

	mods {
		"${project.mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

tasks.register('runData') {
	group = 'mod development'
	description = 'Alias for runClientData'
	dependsOn(tasks.named('runClientData'))
}

tasks.register('prepareDataRun') {
	group = 'mod development'
	description = 'Alias for prepareClientDataRun'
	dependsOn(tasks.named('prepareClientDataRun'))
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

def replaceProperties = [
		minecraft_version       : project.minecraft_version,
		minecraft_version_range : project.minecraft_version_range,
		neo_version             : project.neo_version,
		neo_version_range       : project.neo_version_range,
		loader_version_range    : project.loader_version_range,
		mod_id                  : project.mod_id,
		mod_name                : project.mod_name,
		mod_license             : project.mod_license,
		mod_version             : project.mod_version,
		mod_authors             : project.mod_authors,
		mod_description         : project.mod_description,
		mod_homepage_url        : project.mod_homepage_url,
		mod_issue_tracker_url   : project.mod_issue_tracker_url
]

processResources {
	inputs.properties(replaceProperties)

	filesMatching('META-INF/neoforge.mods.toml') {
		expand replaceProperties
	}
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {
	}
}
