plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	id 'net.neoforged.gradle.userdev' version '7.0.116'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenLocal()
	mavenCentral()
}

runs {
	configureEach {
		systemProperty 'forge.logging.markers', 'REGISTRIES'
		systemProperty 'forge.logging.console.level', 'debug'
		modSource project.sourceSets.main
	}

	client {
		systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
	}

	server {
		systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
		programArgument '--nogui'
	}

	gameTestServer {
		systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
	}

	data {
		programArguments.addAll '--mod', project.mod_id, '--all',
				'--output', file('src/generated/resources/').getAbsolutePath(),
				'--existing', file('src/main/resources/').getAbsolutePath()
	}
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

java {
	toolchain.languageVersion = JavaLanguageVersion.of(17)
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

dependencies {
	implementation "net.neoforged:neoforge:${project.neo_version}"
}

def replaceProperties = [
		minecraft_version       : project.minecraft_version,
		minecraft_version_range : project.minecraft_version_range,
		neo_version             : project.neo_version,
		neo_version_range       : project.neo_version_range,
		loader_version_range    : project.loader_version_range,
		mod_id                  : project.mod_id,
		mod_name                : project.mod_name,
		mod_license             : project.mod_license,
		mod_version             : project.mod_version,
		mod_authors             : project.mod_authors,
		mod_description         : project.mod_description,
		mod_homepage_url        : project.mod_homepage_url,
		mod_issue_tracker_url   : project.mod_issue_tracker_url,
		pack_format_number      : project.pack_format_number
]

tasks.withType(ProcessResources).configureEach {
	inputs.properties(replaceProperties)

	filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
		expand replaceProperties + [project: project]
	}
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {
	}
}
